using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerMovement : MonoBehaviour
{

    public Animator animator;
    public CharacterController2D controller;

    public float runspeed = 40f;
    float horizontalMove = 0f;
    bool jump = false;
    bool crouch = false;
    // Start is called before the first frame update

    // Update is called once per frame
    void Update()
    {
        horizontalMove = Input.GetAxisRaw("Horizontal") * runspeed;
        animator.SetFloat("Speed", Mathf.Abs(horizontalMove));
        if (Input.GetButtonDown("Jump")){
            jump = true;
            animator.SetBool("Jumping", true);
        }
        if (Input.GetButtonDown("Vertical")){
            crouch = true;
        }
        else if(Input.GetButtonUp("Vertical")){
            crouch = false;
        }
        
    }
 
        public void OnCrouching(bool isCrouching){
        animator.SetBool("Crouching", isCrouching);
    }

    public void OnLanding(){
        animator.SetBool("Jumping", false);
    }


    void FixedUpdate(){
        controller.Move(horizontalMove * Time.fixedDeltaTime, crouch, jump);
        jump = false;         
    }
}
